// lib/data/services/report_pdf_service.dart
// PDF generation for SEO Lens reports

import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/report_data.dart';

class ReportPdfService {
  /// Build a PDF report from report data
  Future<Uint8List> buildReportPdf(ReportData data) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(data, context),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildSummarySection(data),
          pw.SizedBox(height: 20),
          _buildHealthBreakdown(data),
          pw.SizedBox(height: 20),
          _buildIssuesSection(data),
          pw.SizedBox(height: 20),
          _buildPagesSection(data),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(ReportData data, pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 20),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'SEO Lens Report',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#1e293b'),
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                data.domain.name,
                style: pw.TextStyle(
                  fontSize: 16,
                  color: PdfColor.fromHex('#64748b'),
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              if (data.domain.lastScannedAt != null)
                pw.Text(
                  'Last scanned: ${DateFormat.yMMMd().format(data.domain.lastScannedAt!.toLocal())}',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColor.fromHex('#94a3b8'),
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 20),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by SEO Lens - seolens.io',
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColor.fromHex('#94a3b8'),
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColor.fromHex('#94a3b8'),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSummarySection(ReportData data) {
    final domain = data.domain;
    final healthScore = domain.healthScore ?? 0;
    final healthColor = healthScore >= 80
        ? PdfColor.fromHex('#22c55e')
        : healthScore >= 60
            ? PdfColor.fromHex('#f59e0b')
            : PdfColor.fromHex('#ef4444');

    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#f8fafc'),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _buildStatBox('Health Score', '$healthScore', healthColor),
          _buildStatBox(
            'Pages Scanned',
            '${domain.totalPagesScanned ?? 0}',
            PdfColor.fromHex('#3b82f6'),
          ),
          _buildStatBox(
            'Issues Found',
            '${data.suggestions.length}',
            data.suggestions.isNotEmpty
                ? PdfColor.fromHex('#f59e0b')
                : PdfColor.fromHex('#22c55e'),
          ),
          if (domain.uptime24hPercent != null)
            _buildStatBox(
              'Uptime (24h)',
              '${domain.uptime24hPercent!.toStringAsFixed(1)}%',
              domain.uptime24hPercent! >= 99
                  ? PdfColor.fromHex('#22c55e')
                  : PdfColor.fromHex('#f59e0b'),
            ),
        ],
      ),
    );
  }

  pw.Widget _buildStatBox(String label, String value, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 28,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 10,
            color: PdfColor.fromHex('#64748b'),
          ),
        ),
      ],
    );
  }

  pw.Widget _buildHealthBreakdown(ReportData data) {
    final domain = data.domain;
    final total = domain.totalPagesScanned ?? 1;

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Health Breakdown',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#1e293b'),
          ),
        ),
        pw.SizedBox(height: 12),
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColor.fromHex('#e2e8f0')),
            borderRadius: pw.BorderRadius.circular(8),
          ),
          child: pw.Column(
            children: [
              _buildBreakdownRow(
                'Pages with Title',
                total - (domain.pagesMissingTitle ?? 0),
                total,
              ),
              pw.SizedBox(height: 8),
              _buildBreakdownRow(
                'Pages with Meta Description',
                total - (domain.pagesMissingMeta ?? 0),
                total,
              ),
              pw.SizedBox(height: 8),
              _buildBreakdownRow(
                'Pages with H1',
                total - (domain.pagesMissingH1 ?? 0),
                total,
              ),
              pw.SizedBox(height: 8),
              _buildBreakdownRow(
                'Successful Responses (2xx)',
                domain.pages2xx ?? 0,
                total,
              ),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _buildBreakdownRow(String label, int value, int total) {
    final percentage = total > 0 ? (value / total * 100) : 100.0;
    final color = percentage >= 80
        ? PdfColor.fromHex('#22c55e')
        : percentage >= 60
            ? PdfColor.fromHex('#f59e0b')
            : PdfColor.fromHex('#ef4444');

    return pw.Row(
      children: [
        pw.Expanded(
          flex: 2,
          child: pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 11,
              color: PdfColor.fromHex('#475569'),
            ),
          ),
        ),
        pw.Expanded(
          flex: 3,
          child: pw.Stack(
            children: [
              pw.Container(
                height: 8,
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#e2e8f0'),
                  borderRadius: pw.BorderRadius.circular(4),
                ),
              ),
              pw.Container(
                height: 8,
                width: percentage * 1.5,
                decoration: pw.BoxDecoration(
                  color: color,
                  borderRadius: pw.BorderRadius.circular(4),
                ),
              ),
            ],
          ),
        ),
        pw.SizedBox(width: 12),
        pw.Text(
          '$value/$total',
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#1e293b'),
          ),
        ),
      ],
    );
  }

  pw.Widget _buildIssuesSection(ReportData data) {
    if (data.suggestions.isEmpty) {
      return pw.Container(
        padding: const pw.EdgeInsets.all(16),
        decoration: pw.BoxDecoration(
          color: PdfColor.fromHex('#f0fdf4'),
          borderRadius: pw.BorderRadius.circular(8),
        ),
        child: pw.Row(
          children: [
            pw.Text(
              'No issues found!',
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: PdfColor.fromHex('#16a34a'),
              ),
            ),
          ],
        ),
      );
    }

    final groupedSuggestions = data.suggestionsByType;

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Issues Found (${data.suggestions.length})',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#1e293b'),
          ),
        ),
        pw.SizedBox(height: 12),
        ...groupedSuggestions.entries.map((entry) {
          final typeName = entry.value.first.typeName;
          final count = entry.value.length;
          final severity = entry.value.first.severity ?? 'medium';
          final severityColor = severity == 'high'
              ? PdfColor.fromHex('#ef4444')
              : severity == 'medium'
                  ? PdfColor.fromHex('#f59e0b')
                  : PdfColor.fromHex('#3b82f6');

          return pw.Container(
            margin: const pw.EdgeInsets.only(bottom: 8),
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColor.fromHex('#e2e8f0')),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              children: [
                pw.Container(
                  width: 8,
                  height: 8,
                  decoration: pw.BoxDecoration(
                    color: severityColor,
                    shape: pw.BoxShape.circle,
                  ),
                ),
                pw.SizedBox(width: 12),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        typeName,
                        style: pw.TextStyle(
                          fontSize: 12,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromHex('#1e293b'),
                        ),
                      ),
                      pw.SizedBox(height: 2),
                      pw.Text(
                        '$count ${count == 1 ? 'page' : 'pages'} affected',
                        style: pw.TextStyle(
                          fontSize: 10,
                          color: PdfColor.fromHex('#64748b'),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          );
        }),
      ],
    );
  }

  pw.Widget _buildPagesSection(ReportData data) {
    if (data.pages.isEmpty) {
      return pw.Container();
    }

    // Show top 20 pages
    final pagesToShow = data.pages.take(20).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Pages Overview',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#1e293b'),
          ),
        ),
        pw.SizedBox(height: 12),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColor.fromHex('#e2e8f0')),
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(4),
            2: const pw.FlexColumnWidth(1),
            3: const pw.FlexColumnWidth(1),
          },
          children: [
            pw.TableRow(
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#f1f5f9'),
              ),
              children: [
                _buildTableHeader('Path'),
                _buildTableHeader('Title'),
                _buildTableHeader('Status'),
                _buildTableHeader('Issues'),
              ],
            ),
            ...pagesToShow.map((page) => pw.TableRow(
                  children: [
                    _buildTableCell(page.path),
                    _buildTableCell(page.title ?? '-'),
                    _buildTableCell(
                      page.statusCode?.toString() ?? '-',
                      color: page.isError
                          ? PdfColor.fromHex('#ef4444')
                          : null,
                    ),
                    _buildTableCell(
                      page.issueCount.toString(),
                      color: page.hasIssues
                          ? PdfColor.fromHex('#f59e0b')
                          : PdfColor.fromHex('#22c55e'),
                    ),
                  ],
                )),
          ],
        ),
        if (data.pages.length > 20)
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 8),
            child: pw.Text(
              '... and ${data.pages.length - 20} more pages',
              style: pw.TextStyle(
                fontSize: 10,
                fontStyle: pw.FontStyle.italic,
                color: PdfColor.fromHex('#64748b'),
              ),
            ),
          ),
      ],
    );
  }

  pw.Widget _buildTableHeader(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
          color: PdfColor.fromHex('#475569'),
        ),
      ),
    );
  }

  pw.Widget _buildTableCell(String text, {PdfColor? color}) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          color: color ?? PdfColor.fromHex('#1e293b'),
        ),
        maxLines: 2,
        overflow: pw.TextOverflow.clip,
      ),
    );
  }
}
